### ISSUE TITLE
"Template fragment" component in Htmxor

### ISSUE THREAD

**Issue by egil** [egil/Htmxor#25]
[UPDATED: combined a bunch of comments below into a general description/issue].

Htmxor needs a good way to do "[template fragments](https://htmx.org/essays/template-fragments/)". The library currently have a very rough first attempt, `<HtmxPartial>`. It may need a better name and certainly more features.

Let me start by explaining how `<HtmxPartial>` works right now.

Lets use this as the example:

```razor
@page "/counter"
<PageTitle>Counter</PageTitle>
<div id="counter">
    <HtmxPartial>
        <p role="status">
            Current count: @CurrentCount
        </p>
        <button class="btn btn-primary"
                hx-put="/counter"
                hx-vals='{ "CurrentCount": @(CurrentCount) }'
                hx-target="#counter"
                @onput="IncrementCount">
            Click me
        </button>
    </HtmxPartial>
</div>

@code {
    [SupplyParameterFromForm]
    private int CurrentCount { get; set; } = 0;

    private void IncrementCount(HtmxContextEventArgs args)
    {
        CurrentCount++;
    }
}
```

### Normal request or hx-boosted request
During a normal request or hx-boosted request, the full component tree is rendered, i.e. starting with `App.razor`, all the way down to the `Counter.razor` page.

Here the full component tree is rendered out, including `<HtmxPartial>` and its child content.

### hx-request to /counter
When a hx-request is received that targets the <Counter> component, that component's component-tree is searched, and since a <HtmxPartial> component is found whose `[Parameter] public bool Condition { get; set; } = true;` returns true, only that `<HtmxPartial>` component and its children is rendered.

### Normal request or htmx request
During rendering, if a <HtmxPartial> component is reached, its `Condition` parameter is checked, and if it returns `false`, the component and its children is not rendered.

This happens during both normal and htmx requests.

A more detailed discussion of the proposed improvements is in the comment https://github.com/egil/Htmxor/issues/25#issuecomment-2088498304 below.

**Comment by tanczosm** [comment]
What exactly is the purpose of HxPartial?

**Comment by egil** [comment]
The purpose is to have parts of a component that only render conditionally, or more generally, they are an implementation of https://htmx.org/essays/template-fragments/.

For example:

https://github.com/egil/Htmxor/blob/fba91392cf8d13c598896406484da9efbe795698/samples/MinimalHtmxorApp/Components/Pages/Counter.razor#L1-L25)

Here, on a full-page request, the entire markup is rendered. On htmx requests, only the child content of the `HxPartial` is rendered.

**Comment by tanczosm** [comment]
This section is really worth thinking about a bit regarding some of the various angles you could approach.  The idea of "full page request" needs to be carefully considered, because I could see nested partials being used frequently.

This actually was the core idea I originally wanted with the HxSwappable component, because typically the areas that you would do this with align with either standard swaps or out-of-bound swaps. To make them work you always need a container with an id and then if the request is HTMX you can add the OOB hx-swap-oob="true" attribute to the response without any bad effects even if the swap isn't oob.

A typical use case on a page might have more than one "HxSwappable" section akin to your HtmxPartial, so the rendered result just needs to be:
1. If htmx then consecutive renders of the swappable containers with each having hx-swap-oob="true" added so they each neatly swap into the right places
2. If not htmx, render the whole page inline

The other thing I would have done would be to make sure that each HxSwappable/HtmxPartial can be directly routable somehow (by it's container id?).  

If the page is: /news/ then this routes to /news/weather or /news/?hxs=weather or something.  I'm not sure about the easiest solution to this problem.
```html
<HxSwappable Id="weather"></HxSwappable>
```

**The other major factor to consider is the flow of data to these sections**.  Typically you need to compose these swappable sections because they enclose components that will experience state changes. I've most typically made use of them when I have a section of page that may take longer to render than the rest of the page because there is some higher level of latency when loading data and you want to present something to the user (like a skeleton).

React has a component called [Suspense](https://react.dev/reference/react/Suspense) that has similar effects to what I'd love out of a Swappable section.  

Perhaps something like this:
```html
<HxSwappable Id="videos" Mode=@RenderModes.Lazy>
   <Fallback>Video skeleton page here</Fallback>
   <ChildContent>Long loading content</ChildContent>
</HxSwappable>
```

This is spitballing here but when rendering HxSwappable components if the render mode is Lazy then render Fallback only (ignoring ChildContent rendering completely) and use the [htmx lazy loading pattern](https://htmx.org/examples/lazy-load/) to load in content.  When rendering that swappable from htmx then render the content directly, ignoring fallback.

The other idea which is a more htmx friendly alternative to streaming, would be:

When the render mode is RenderModes.Lazy (or whatever) and the current route isn't directly to this component, then you immediately render fallback and begin rendering ChildContent out-of-band, making the result available on a cached basis via some unique url.  That way the user gets the response 

e.g.
On first load the above HxSwappable component renders as:
```html
<div id="hx_videos" hx-get="/special/deferred/render/url/8c691763-21b2-4c78-b0e4-5f7236fab91d" hx-trigger="load">
    Video skeleton page here
</div>
```

Then the page loads, a request is made by htmx to /special/deferred/render/url/8c691763-21b2-4c78-b0e4-5f7236fab91d and retrieves the result of rendering the ChildContent.

If this isn't feasible then at least having the Swappable component directly routable would work.

**Comment by egil** [comment]
I like your ideas suggested in https://github.com/egil/Htmxor/issues/25#issuecomment-2088376473. Good stuff!

But, I want to see if we can figure out a "generalized fragment/partial/naming is hard" component (I'll keep calling this HtmxPartial until we figure out a better name), that e.g. a `<HxSwappable>` component can inherit from, or another 3rd party custom component can inherit from, that enables all your good ideas.

Because it would be great if `<HtmxPartial>` is the only component type the `HtmxRenderer` needs to know about.

So, let's establish some rules for `<HtmxPartial>`. Here are my current suggestions:

**During normal/boosted requests:**

1. `<HtmxPartial Condition=true>` is the default, e.g. the same as `<HtmxPartial>`
2. `<HtmxPartial>` is only rendered if its `Condition` returns `true`.
3. Multiple `<HtmxPartial>` component can render during the same request. For example:

    ```razor
    <HtmxPartial Condition=true>Foo</HtmxPartial>
    <HtmxPartial Condition=false>Bar</HtmxPartial>
    <HtmxPartial Condition=true>Baz</HtmxPartial>
    ```
    
    This will result in `Foo Baz` being returned.

5. A `<HtmxPartial>` does not render if it is a child of inside another `<HtmxPartial Condition=false>`, independent of what its Condition parameter returns. For example:

    ```razor
    <HtmxPartial Condition=false>Foo
      <HtmxPartial Condition=true>Bar</HtmxPartial>
    </HtmxPartial>    
    <HtmxPartial Condition=true>Baz</HtmxPartial>
    ```
    
    This will result in `Baz` being returned. Equally:

    ```razor
    <HtmxPartial Condition=true>Foo
      <HtmxPartial Condition=false>Bar</HtmxPartial>
    </HtmxPartial>    
    <HtmxPartial Condition=true>Baz</HtmxPartial>
    ```

    This will result in `Foo Baz` being returned.

**Specifically during HX requests:**

6. If the target component's component tree does NOT contain any `<HtmxPartial>` components, the full component tree is rendered out, e.g. a request to `/component-without-partials`:

    ```razor
    @page "/component-without-partials"
    <h1>hello world</h1>
    <ChildComponent Message="hi" />
    ```  
   
    Will result in both `<ComponentWithoutPartials>` and all its children being rendered.

7. If the target component's component tree contains one or more `<HtmxPartial>` whose returns on return `true`, then ONLY these `<HtmxPartial>` components are rendered. E.g. a request to `/component-partials`:

    ```razor
    @page "/component-partials"
    <h1>hello world</h1>
    <HtmxPartial>
      <ChildComponent Message="hi" />
    </HtmxPartial>
    ```  
   
    This will result in both `<ChildComponent >` being rendered.

8. If the target component defines a `HxLayout`, then that layout is always rendered, independent of whether there exists `<HtmxPartial>` components in the render tree or not. For example:

    ```razor
    @page "/component-without-partials"
    @attribute [HxLayout(typeof(HtmxorLayout)]
    <h1>hello world</h1>
    <ChildComponent Message="hi" />
    ```  

    ```razor
    @page "/component-partials"
    @attribute [HxLayout(typeof(HtmxorLayout)]
    <h1>hello world</h1>
    <HtmxPartial>
      <ChildComponent Message="hi" />
    </HtmxPartial>
    ```  

   will both render any target component as a child of the `HtmxorLayout` component.

This should enable all your ideas through custom components that inherit from `<HtmxPartial>`.

Currently, the Htmxor does these things:

- 1 = OK
- 2 = OK
- 3 = Missing
- 4 = Partially, only for the first <HtmxPartial>
- 5 = Partially, only for the first <HtmxPartial condition=true>
- 6 = OK
- 7 = Partially, only for the first <HtmxPartial>
- 8 = Partially, only for normal requests

**Comment by tanczosm** [comment]
What is the mechanism for targeting that HtmxPartial component?

> ### Normal request or hx-boosted request
> During a normal request or hx-boosted request, the full component tree is rendered, i.e. starting with `App.razor`, all the way down to the `Counter.razor` page.

This is incorrect.  On an hx-boosted request the rendered output can still target a particular selector.  The documentation doesn't give you much to indicate it but hx-target is still adhered to along with hx-swap as well.  Even if hx-target is body then hx-boosted requests only replace the body of the current page without changing the url (used for non-GET requests).  If hx-target is "window" or empty (?) then it's a full page request.

For example:
```html
<a href="/home" hx-swap="innerHTML transition:true scroll:main:top show:none" hx-boost="true" hx-target="#main_content">Home</a>
```

This would load the content at url /home as boosted, swapping it into #main_content with a transition, immediately setting the scrollbar to the top of main without any animation, and overriding any default show scroll animations.  This would allow you to load content into a particular div just as you would with hx-get. 

I see you added something more so I'm going to read that before adding anything further.

**Comment by egil** [comment]
Let's keep how to handle hx-boost out of this discussion. Moved to issue #26.

**Comment by egil** [comment]
With the rules above in mind, lets try to implement HtmxSwappable (completely untested):

```razor
@using Htmxor.Http
@inherits PartialBase
@inject HtmxContext Context
@code {
    [Parameter, EditorRequired]
    public required RenderFragment Loading { get; set; }

    [Parameter, EditorRequired]
    public required RenderFragment ChildContent { get; set; }

    [Parameter, EditorRequired]
    public required string Id { get; set; }

    [Parameter]
    public bool Lazy { get; set; }

    // Render both during normal and htmx requests
    protected internal override bool ShouldRender() => true;
}
@if (Lazy)
{
    if (Context.Request.IsHtmxRequest)
    {
        <div id="@Id" hx-target="#@Id" hx-swap="innerHTML" hx-swap-oob="true">
            @ChildContent
        </div>
    }
    else
    {
        <div id="@Id" hx-target="#@Id" hx-get="@Context.Request.CurrentURL.PathAndQuery" hx-trigger="load">
            @Loading
        </div>
    }
}
else
{
    <div id="@Id">
        @ChildContent
    </div>
}
```

**Comment by tanczosm** [comment]
The base component idea works.  I'm going to parse through your ideas and see if anything jumps out that is missing.  

Quick question, if I nest a component inside of a partial with Condition=false, no lifecycle methods for that component are ever called correct?

**Comment by egil** [comment]
> Quick question, if I nest a component inside of a partial with Condition=false, no lifecycle methods for that component are ever called correct?

This is an interesting discussion.

We could go with **no**, meaning that `SetParameterAsync` (which kicks off all other life cycle methods, if any) is never called on child components, meaning no render tree is created, thus, the child components and markup/elements are never instantiated and never exist.

However, it could be that the element that was the trigger for the hx-request, e.g. `<button hx-get="/url" @onget=(() => some logic here)>BTN</button>`, is the child of a partial with Condition=false. In this case, the event handler would never be recreated and Htmxor will not be able to call it.

An alternative is to go with an approach similar to Blazor's `[ComponentBase.ShouldRender()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.shouldrender?view=aspnetcore-8.0)`. It will allow a single render and any number of invocations of life cycle methods. This could be useful if "condition" is determined dynamically based on async operations.

Ultimately, when it comes time to produce markup that will be sent to client, the renderer will not generate markup from components inside partials with condition false, but any child components and their render trees will be created.

**Comment by egil** [comment]
The condition value is cascading in a sense that if a parent component is true, then all children will inherit that render condition unless they override.

**Comment by tanczosm** [comment]
That makes sense. I like that approach. 

Should the xmldoc param doc say implements IConditionalOutput?.
```csharp
    /// <param name="hasConditionalChildren">Whether this component has any children that implements <paramref name="hasConditionalChildren"/>.</param>
```

**Comment by egil** [comment]
Ok, the core functionality has been merged in. @tanczosm, I would love to get your take on useful components like HtmxSwappable mentioned earlier. But lets create an individual issue for those.
